import emoji
print("Emojis disponíveis:")
print("❤️  - :red_heart:")
print("👍  - :thumbs_up:")
print("🤔  - :thinking_face:")
print("🥳  - :partying_face:")
print("😎 - :smiling_face_with_sunglasses:")
print("😂 - :face_with_tears_of_joy:")
print("😍 - :smiling_face_with_heart_eyes:")
print("🚀 - :rocket:")
frase = input("Digite uma frase e ela será emojizada:")
frase_emojizada = emoji.emojize(frase)
print("Frase emojizada:")
print(frase_emojizada)
